// Mock profiles for UI development — used in discover feed when Supabase auth is not yet wired
export const MOCK_PROFILES = [
  {
    id: "11111111-0001-0001-0001-000000000001",
    display_name: "Amara Okafor",
    avatar_url: "https://i.pravatar.cc/150?img=1",
    age: 19,
    gender: "female" as const,
    city: "Lagos",
    university: "UNILAG",
    year_of_study: 2,
    min_budget: 70000,
    max_budget: 120000,
    move_in_date: "2026-07-01",
    lifestyle_tags: ["studious", "homebody", "religious"],
    sleep_schedule: "early_bird" as const,
    cleanliness: "very_tidy" as const,
    noise_pref: "quiet" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: true,
    student_verified: true,
    last_seen_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0002-0002-0002-000000000002",
    display_name: "Emeka Nwosu",
    avatar_url: "https://i.pravatar.cc/150?img=3",
    age: 21,
    gender: "male" as const,
    city: "Abuja",
    university: "UNIABUJA",
    year_of_study: 3,
    min_budget: 50000,
    max_budget: 80000,
    move_in_date: "2026-08-01",
    lifestyle_tags: ["gamer", "studious", "homebody"],
    sleep_schedule: "night_owl" as const,
    cleanliness: "relaxed" as const,
    noise_pref: "moderate" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: false,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 3600000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0003-0003-0003-000000000003",
    display_name: "Fatimah Bello",
    avatar_url: "https://i.pravatar.cc/150?img=5",
    age: 20,
    gender: "female" as const,
    city: "Lagos",
    university: "UNILAG",
    year_of_study: 2,
    min_budget: 60000,
    max_budget: 100000,
    move_in_date: "2026-07-01",
    lifestyle_tags: ["religious", "studious", "homebody"],
    sleep_schedule: "early_bird" as const,
    cleanliness: "tidy" as const,
    noise_pref: "very_quiet" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: false,
    student_verified: true,
    last_seen_at: new Date(Date.now() - 1800000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0004-0004-0004-000000000004",
    display_name: "Chidi Eze",
    avatar_url: "https://i.pravatar.cc/150?img=7",
    age: 22,
    gender: "male" as const,
    city: "Enugu",
    university: "UNN",
    year_of_study: 4,
    min_budget: 40000,
    max_budget: 70000,
    move_in_date: "2026-09-01",
    lifestyle_tags: ["foodie", "social", "athletic"],
    sleep_schedule: "flexible" as const,
    cleanliness: "tidy" as const,
    noise_pref: "moderate" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: true,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 10800000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0005-0005-0005-000000000005",
    display_name: "Ngozi Adeyemi",
    avatar_url: "https://i.pravatar.cc/150?img=9",
    age: 23,
    gender: "female" as const,
    city: "Ibadan",
    university: "UI",
    year_of_study: 5,
    min_budget: 55000,
    max_budget: 90000,
    move_in_date: "2026-07-01",
    lifestyle_tags: ["studious", "homebody", "traveler"],
    sleep_schedule: "night_owl" as const,
    cleanliness: "very_tidy" as const,
    noise_pref: "very_quiet" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: false,
    student_verified: true,
    last_seen_at: new Date(Date.now() - 2700000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0006-0006-0006-000000000006",
    display_name: "Tunde Afolabi",
    avatar_url: "https://i.pravatar.cc/150?img=11",
    age: 21,
    gender: "male" as const,
    city: "Lagos",
    university: "LASU",
    year_of_study: 3,
    min_budget: 45000,
    max_budget: 75000,
    move_in_date: "2026-08-01",
    lifestyle_tags: ["social", "traveler", "foodie"],
    sleep_schedule: "flexible" as const,
    cleanliness: "relaxed" as const,
    noise_pref: "lively" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: true,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 18000000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0007-0007-0007-000000000007",
    display_name: "Adaeze Okoro",
    avatar_url: "https://i.pravatar.cc/150?img=13",
    age: 22,
    gender: "female" as const,
    city: "Port Harcourt",
    university: "UNIPORT",
    year_of_study: 3,
    min_budget: 80000,
    max_budget: 150000,
    move_in_date: "2026-07-01",
    lifestyle_tags: ["studious", "religious", "homebody"],
    sleep_schedule: "early_bird" as const,
    cleanliness: "very_tidy" as const,
    noise_pref: "quiet" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: false,
    student_verified: true,
    last_seen_at: new Date(Date.now() - 1200000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0008-0008-0008-000000000008",
    display_name: "Ibrahim Musa",
    avatar_url: "https://i.pravatar.cc/150?img=15",
    age: 20,
    gender: "male" as const,
    city: "Kano",
    university: "BUK",
    year_of_study: 2,
    min_budget: 30000,
    max_budget: 55000,
    move_in_date: "2026-09-01",
    lifestyle_tags: ["religious", "studious", "homebody"],
    sleep_schedule: "early_bird" as const,
    cleanliness: "tidy" as const,
    noise_pref: "quiet" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: false,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 21600000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0009-0009-0009-000000000009",
    display_name: "Chioma Nwachukwu",
    avatar_url: "https://i.pravatar.cc/150?img=17",
    age: 21,
    gender: "female" as const,
    city: "Abuja",
    university: "BAZE",
    year_of_study: 3,
    min_budget: 65000,
    max_budget: 110000,
    move_in_date: "2026-08-01",
    lifestyle_tags: ["social", "foodie", "traveler"],
    sleep_schedule: "night_owl" as const,
    cleanliness: "tidy" as const,
    noise_pref: "moderate" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: true,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 3600000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0010-0010-0010-000000000010",
    display_name: "Segun Olawale",
    avatar_url: "https://i.pravatar.cc/150?img=19",
    age: 23,
    gender: "male" as const,
    city: "Lagos",
    university: "UNILAG",
    year_of_study: 4,
    min_budget: 60000,
    max_budget: 100000,
    move_in_date: "2026-07-01",
    lifestyle_tags: ["gamer", "social", "homebody"],
    sleep_schedule: "flexible" as const,
    cleanliness: "relaxed" as const,
    noise_pref: "moderate" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: true,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 7200000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0011-0011-0011-000000000011",
    display_name: "Kemi Adebayo",
    avatar_url: "https://i.pravatar.cc/150?img=21",
    age: 20,
    gender: "female" as const,
    city: "Ibadan",
    university: "UI",
    year_of_study: 2,
    min_budget: 50000,
    max_budget: 85000,
    move_in_date: "2026-09-01",
    lifestyle_tags: ["studious", "vegetarian", "athletic"],
    sleep_schedule: "early_bird" as const,
    cleanliness: "very_tidy" as const,
    noise_pref: "quiet" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: false,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 14400000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0012-0012-0012-000000000012",
    display_name: "Uche Obiechina",
    avatar_url: "https://i.pravatar.cc/150?img=23",
    age: 22,
    gender: "male" as const,
    city: "Nsukka",
    university: "UNN",
    year_of_study: 4,
    min_budget: 35000,
    max_budget: 60000,
    move_in_date: "2026-08-01",
    lifestyle_tags: ["gamer", "studious", "social"],
    sleep_schedule: "night_owl" as const,
    cleanliness: "relaxed" as const,
    noise_pref: "moderate" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: true,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 10800000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0013-0013-0013-000000000013",
    display_name: "Halima Abdullahi",
    avatar_url: "https://i.pravatar.cc/150?img=25",
    age: 21,
    gender: "female" as const,
    city: "Abuja",
    university: "UNIABUJA",
    year_of_study: 3,
    min_budget: 40000,
    max_budget: 70000,
    move_in_date: "2026-07-01",
    lifestyle_tags: ["religious", "homebody", "studious"],
    sleep_schedule: "early_bird" as const,
    cleanliness: "tidy" as const,
    noise_pref: "very_quiet" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: false,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 25200000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0014-0014-0014-000000000014",
    display_name: "David Akintola",
    avatar_url: "https://i.pravatar.cc/150?img=27",
    age: 20,
    gender: "male" as const,
    city: "Lagos",
    university: "LASU",
    year_of_study: 2,
    min_budget: 35000,
    max_budget: 60000,
    move_in_date: "2026-09-01",
    lifestyle_tags: ["athletic", "social", "studious"],
    sleep_schedule: "flexible" as const,
    cleanliness: "tidy" as const,
    noise_pref: "moderate" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: true,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 28800000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0015-0015-0015-000000000015",
    display_name: "Blessing Onyeka",
    avatar_url: "https://i.pravatar.cc/150?img=29",
    age: 22,
    gender: "female" as const,
    city: "Enugu",
    university: "ESUT",
    year_of_study: 3,
    min_budget: 45000,
    max_budget: 75000,
    move_in_date: "2026-07-01",
    lifestyle_tags: ["religious", "studious", "homebody"],
    sleep_schedule: "early_bird" as const,
    cleanliness: "very_tidy" as const,
    noise_pref: "quiet" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: false,
    student_verified: true,
    last_seen_at: new Date(Date.now() - 1800000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0016-0016-0016-000000000016",
    display_name: "Michael Obi",
    avatar_url: "https://i.pravatar.cc/150?img=31",
    age: 23,
    gender: "male" as const,
    city: "Port Harcourt",
    university: "RSU",
    year_of_study: 4,
    min_budget: 55000,
    max_budget: 95000,
    move_in_date: "2026-08-01",
    lifestyle_tags: ["social", "traveler", "gamer"],
    sleep_schedule: "night_owl" as const,
    cleanliness: "relaxed" as const,
    noise_pref: "lively" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: true,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 3600000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0017-0017-0017-000000000017",
    display_name: "Sade Fashola",
    avatar_url: "https://i.pravatar.cc/150?img=33",
    age: 23,
    gender: "female" as const,
    city: "Lagos",
    university: "UNILAG",
    year_of_study: 4,
    min_budget: 75000,
    max_budget: 130000,
    move_in_date: "2026-07-01",
    lifestyle_tags: ["studious", "foodie", "homebody"],
    sleep_schedule: "early_bird" as const,
    cleanliness: "very_tidy" as const,
    noise_pref: "quiet" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: false,
    student_verified: true,
    last_seen_at: new Date(Date.now() - 900000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0018-0018-0018-000000000018",
    display_name: "Kenny Okonkwo",
    avatar_url: "https://i.pravatar.cc/150?img=35",
    age: 22,
    gender: "male" as const,
    city: "Abuja",
    university: "BAZE",
    year_of_study: 3,
    min_budget: 70000,
    max_budget: 120000,
    move_in_date: "2026-08-01",
    lifestyle_tags: ["social", "gamer", "traveler"],
    sleep_schedule: "flexible" as const,
    cleanliness: "tidy" as const,
    noise_pref: "moderate" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: true,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 7200000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0019-0019-0019-000000000019",
    display_name: "Nkechi Okafor",
    avatar_url: "https://i.pravatar.cc/150?img=37",
    age: 21,
    gender: "female" as const,
    city: "Ibadan",
    university: "UI",
    year_of_study: 3,
    min_budget: 50000,
    max_budget: 80000,
    move_in_date: "2026-09-01",
    lifestyle_tags: ["studious", "vegetarian", "traveler"],
    sleep_schedule: "flexible" as const,
    cleanliness: "tidy" as const,
    noise_pref: "quiet" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: true,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 14400000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0020-0020-0020-000000000020",
    display_name: "Frank Egwuatu",
    avatar_url: "https://i.pravatar.cc/150?img=39",
    age: 20,
    gender: "male" as const,
    city: "Enugu",
    university: "UNN",
    year_of_study: 2,
    min_budget: 30000,
    max_budget: 55000,
    move_in_date: "2026-08-01",
    lifestyle_tags: ["social", "athletic", "traveler"],
    sleep_schedule: "night_owl" as const,
    cleanliness: "messy" as const,
    noise_pref: "lively" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: true,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 32400000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0021-0021-0021-000000000021",
    display_name: "Yetunde Balogun",
    avatar_url: "https://i.pravatar.cc/150?img=41",
    age: 20,
    gender: "female" as const,
    city: "Lagos",
    university: "LASU",
    year_of_study: 2,
    min_budget: 45000,
    max_budget: 70000,
    move_in_date: "2026-09-01",
    lifestyle_tags: ["studious", "religious", "homebody"],
    sleep_schedule: "early_bird" as const,
    cleanliness: "tidy" as const,
    noise_pref: "quiet" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: false,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 10800000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0022-0022-0022-000000000022",
    display_name: "Chuka Anyanwu",
    avatar_url: "https://i.pravatar.cc/150?img=43",
    age: 22,
    gender: "male" as const,
    city: "Port Harcourt",
    university: "UNIPORT",
    year_of_study: 3,
    min_budget: 50000,
    max_budget: 85000,
    move_in_date: "2026-07-01",
    lifestyle_tags: ["foodie", "athletic", "social"],
    sleep_schedule: "flexible" as const,
    cleanliness: "relaxed" as const,
    noise_pref: "moderate" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: true,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 18000000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0023-0023-0023-000000000023",
    display_name: "Aisha Garba",
    avatar_url: "https://i.pravatar.cc/150?img=45",
    age: 18,
    gender: "female" as const,
    city: "Kano",
    university: "BUK",
    year_of_study: 1,
    min_budget: 25000,
    max_budget: 45000,
    move_in_date: "2026-09-01",
    lifestyle_tags: ["religious", "studious", "homebody"],
    sleep_schedule: "early_bird" as const,
    cleanliness: "very_tidy" as const,
    noise_pref: "very_quiet" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: false,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 36000000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0024-0024-0024-000000000024",
    display_name: "Rotimi Adeleke",
    avatar_url: "https://i.pravatar.cc/150?img=47",
    age: 23,
    gender: "male" as const,
    city: "Abuja",
    university: "UNIABUJA",
    year_of_study: 4,
    min_budget: 60000,
    max_budget: 100000,
    move_in_date: "2026-08-01",
    lifestyle_tags: ["social", "traveler", "gamer"],
    sleep_schedule: "night_owl" as const,
    cleanliness: "tidy" as const,
    noise_pref: "moderate" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: true,
    student_verified: false,
    last_seen_at: new Date(Date.now() - 7200000).toISOString(),
    onboarding_complete: true,
  },
  {
    id: "11111111-0025-0025-0025-000000000025",
    display_name: "Obiageli Nwobi",
    avatar_url: "https://i.pravatar.cc/150?img=49",
    age: 24,
    gender: "female" as const,
    city: "Ibadan",
    university: "UI",
    year_of_study: 5,
    min_budget: 65000,
    max_budget: 110000,
    move_in_date: "2026-07-01",
    lifestyle_tags: ["athletic", "vegetarian", "traveler"],
    sleep_schedule: "flexible" as const,
    cleanliness: "very_tidy" as const,
    noise_pref: "quiet" as const,
    allows_smoking: false,
    allows_pets: false,
    allows_guests: true,
    student_verified: true,
    last_seen_at: new Date(Date.now() - 3600000).toISOString(),
    onboarding_complete: true,
  },
];
